# Generated by Django 3.0.7 on 2020-07-07 09:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='id_date_issued',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='id_num',
            field=models.CharField(default='', max_length=8, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='id_place_issued',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='id_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Αστυνομική'), (2, 'Διαβατήριο'), (3, 'Στρατιωτική')], default=1),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_company',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_pharmacist',
            field=models.BooleanField(default=False),
        ),
    ]
