# Generated by Django 3.0.7 on 2020-07-07 10:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200707_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='birthdate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
