# Generated by Django 3.0.7 on 2020-07-07 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cell_phone',
            field=models.BigIntegerField(default=0),
        ),
    ]
