# Generated by Django 3.0.7 on 2020-07-07 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_cell_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cell_phone',
            field=models.BigIntegerField(blank=True),
        ),
    ]
