# Generated by Django 3.0.6 on 2020-07-07 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200707_1310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='is_company',
            new_name='is_pharmacy',
        ),
    ]
