# Generated by Django 3.0.7 on 2020-07-09 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_pharmacistprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacistprofile',
            name='doy',
            field=models.CharField(default='', max_length=50),
        ),
    ]
