# Generated by Django 3.0.7 on 2020-10-22 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacist', '0002_auto_20201022_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='active',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='charge',
            name='confirmation_send',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='charge',
            name='desease',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
