# Generated by Django 3.0.7 on 2020-10-22 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacist', '0004_auto_20201022_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='charge_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
