# Generated by Django 3.0.7 on 2021-01-22 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pharmacist', '0007_auto_20201025_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ChargeBlister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=20)),
                ('charge_date', models.DateField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], default=1)),
                ('dosage', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], default=1)),
                ('frequency', models.IntegerField(choices=[(1, '1 φορά την ημέρα'), (2, '2 φορές την ημέρα'), (3, '3 φορές την ημέρα'), (4, '4 φορές την ημέρα'), (5, '1 φορά την εβδομάδα'), (6, '2 φορές την εβδομάδα'), (7, '3 φορές την εβδομάδα')], default=1)),
                ('duration', models.IntegerField(choices=[(1, 'για 7 ημέρες'), (2, 'για 10 ημέρες'), (3, 'για 2 εβδομάδες'), (4, 'για 1 μήνα'), (5, 'για 2 μήνες'), (6, 'για 3 μήνες'), (7, 'για 6 μήνες'), (8, 'για ένα έτος')], default=1)),
            ],
        ),
        migrations.DeleteModel(
            name='Charge',
        ),
    ]
