# Generated by Django 3.0.7 on 2021-01-26 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20200903_1316'),
        ('pharmacist', '0010_auto_20210125_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blister',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.PatientProfile'),
        ),
    ]
