# Generated by Django 3.0.7 on 2021-01-26 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20200903_1316'),
        ('pharmacist', '0011_auto_20210126_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='blister',
            name='pharmacist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.PharmacistProfile'),
        ),
    ]
