# Generated by Django 3.0.7 on 2021-01-28 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacist', '0012_blister_pharmacist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blister',
            name='charge_date',
            field=models.DateField(),
        ),
    ]
