# Generated by Django 3.0.7 on 2021-01-28 19:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacist', '0013_auto_20210128_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blister',
            name='charge_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
