# Generated by Django 3.0.7 on 2021-01-30 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20200903_1316'),
        ('pharmacist', '0014_auto_20210128_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.PatientProfile'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.DoctorProfile'),
        ),
        migrations.DeleteModel(
            name='BlisterPrescription',
        ),
    ]
