# Generated by Django 3.0.7 on 2021-01-30 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_prescription'),
        ('pharmacist', '0015_auto_20210130_0829'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlisterPrescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blister', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pharmacist.Blister')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='doctor.Prescription')),
            ],
        ),
        migrations.DeleteModel(
            name='Prescription',
        ),
    ]
