# Generated by Django 3.0.7 on 2020-09-08 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitoringrequest',
            name='accepted',
        ),
        migrations.AddField(
            model_name='monitoringrequest',
            name='date_accepted',
            field=models.DateField(blank=True, null=True),
        ),
    ]
