# Generated by Django 3.0.7 on 2021-01-30 06:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20200903_1316'),
        ('doctor', '0002_auto_20200908_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_issued', models.DateField(default=django.utils.timezone.now)),
                ('illness', models.CharField(max_length=255)),
                ('medicine', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], default=1)),
                ('dosage', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], default=1)),
                ('frequency', models.IntegerField(choices=[(1, '1 φορά την ημέρα'), (2, '2 φορές την ημέρα'), (3, '3 φορές την ημέρα'), (4, '4 φορές την ημέρα'), (5, '1 φορά την εβδομάδα'), (6, '2 φορές την εβδομάδα'), (7, '3 φορές την εβδομάδα')], default=1)),
                ('duration', models.IntegerField(choices=[(1, 'για 7 ημέρες'), (2, 'για 10 ημέρες'), (3, 'για 2 εβδομάδες'), (4, 'για 1 μήνα'), (5, 'για 2 μήνες'), (6, 'για 3 μήνες'), (7, 'για 6 μήνες'), (8, 'για ένα έτος')], default=1)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.DoctorProfile')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.PatientProfile')),
            ],
        ),
    ]
