# Generated by Django 3.0.7 on 2021-01-30 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_auto_20210130_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='duration',
            field=models.IntegerField(choices=[(1, 'για 7 ημέρες'), (2, 'για 10 ημέρες'), (3, 'για 2 εβδομάδες'), (4, 'για 1 μήνα'), (5, 'για 2 μήνες'), (6, 'για 3 μήνες'), (7, 'για 6 μήνες'), (8, 'για ένα έτος')], default=1),
        ),
    ]
