# Generated by Django 3.0.7 on 2021-01-30 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0008_remove_prescription_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='duration',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='doctor.Duration'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='frequency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='doctor.Frequency'),
        ),
    ]
